### PR TITLE
fix: remove incorrectly tsconfig compilerOptions options

### PR DESCRIPTION
**Pull request by MaikoTan**
A simple fix for our bakabaka LunaY

Firstly introduced in #1

### CODE REVIEW

**Comment by MaikoTan** [comment]
And there are many CI errors on every commits, are they ok?

**Comment by Lipraty** [comment]
> And there are many CI errors on every commits, are they ok?

maybe(

**Review by Lipraty — COMMENTED** [review]
其实......梦梦说应该放 client/tsconfig.json {WU0F(@9Y%O3171(5K{OMXQ

**Comment by MaikoTan** [comment]
Sure, I changed to remove these lines.

**Comment by MaikoTan** [comment]
Generally we recommend to use `Squash and merge` instead of `Create a merge commit` option. You can go to the Settings page of the current repository and unselect `Merge commit` method.

By kindly Maiko for bakabaka LunaY)

**Pull request merged**
